const contenedorCard = document.querySelector("#productos")
const contenedorCarrito = document.querySelector("#contenedor-2")
const btnIrCarrito = document.querySelector("button#ir-carrito")
const btnRefesh = document.querySelector("#refesh")
const totalCompra = document.querySelector("#total-compra")
const datosCarrito = JSON.parse(localStorage.getItem("Carrito")) || []
const lengthCarrito = document.querySelector("#cantidad-carrito")
const productos = []
const carrito = []
const URL = "js/productos.json"
